- name: Setup Prompt
  ansible.builtin.shell: set-prompt github-runner

- name: Create github directory
  ansible.builtin.file:
    path: /actions-runner
    state: directory

- name: Download & Extract Runner
  ansible.builtin.unarchive:
    src: https://github.com/actions/runner/releases/download/v2.317.0/actions-runner-linux-x64-2.317.0.tar.gz
    dest: "/actions-runner"
    remote_src: yes

- name: Download GitHub Cli Repo
  ansible.builtin.get_url:
    src: https://cli.github.com/packages/rpm/gh-cli.repo
    dest: /etc/yum.repos.d/gh-cli.repo

- name: Install github cli
  ansible.builtin.dnf:
    name: gh-cli
    state: latest





