- name: Set prompt
  ansible.builtin.shell: set-prompt vault

- name: Download Vault repo file
  ansible.builtin.get_url:
    url: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    dest: /etc/yum.repos.d/hashicorp.repo

- name: Install Vault
  ansible.builtin.dnf:
    name: vault
    state: latest

- name: Copy vault config
  ansible.builtin.copy:
    src: vault.hcl
    dest: /etc/vault/vault.hcl

- name: Start Vault serice
  ansible.builtin.systemd_service:
    name: vault
    state: restarted
    enabled: yes



